// relidler tools --tool agg --input src/libs/cfg/constants --out src/libs/cfg/cfg-main.ts --recursive --named --strip src/libs/cfg
export {
  PROJECT_ROOT,
  cliVersion,
  cliName,
  tsconfigJson,
  cliConfigJsonc,
  cliConfigJsoncTmp,
  cliConfigJsoncBak,
  cliConfigTs,
  cliConfigTsTmp,
  cliConfigTsBak,
  reliverseOrgBase,
  reliverseOrgRoot,
  cliDomainRoot,
  cliDomainDocs,
  cliDomainEnv,
  homeDir,
  cliHomeDir,
  cliHomeTmp,
  cliHomeRepos,
  memoryPath,
  cliJsrPath,
  useLocalhost,
  DEFAULT_CLI_USERNAME,
  endTitle,
  UNKNOWN_VALUE,
  DEFAULT_DOMAIN,
  RELIVERSE_SCHEMA_DEV,
  RELIVERSE_SCHEMA_URL,
  FALLBACK_ENV_EXAMPLE_URL,
  CONFIG_CATEGORIES,
} from "./constants/cfg-details.js";
export {
  reliverseConfigSchema,
  generateJsonSchema,
  generateSchemaFile,
  defineConfig,
} from "./constants/cfg-schema.js";
export type {
  ReliverseConfig,
  ProjectCategory,
  ProjectSubcategory,
  ProjectFramework,
  ProjectArchitecture,
  RelinterConfirm,
} from "./constants/cfg-types.js";
