// This file is autogenerated by: scripts/src/cmds/bts/cmd.ts
// Do not edit manually - your changes will be overwritten

import { defineArgs, defineCommand } from "@reliverse/dler-launcher";
import { logger } from "@reliverse/dler-logger";
import {
  generateAllPackages,
  generateRootFiles,
  generateRootPackageJson,
  promptMonorepoConfig,
} from "@reliverse/rse-addons";
import { $ } from "bun";
import { init as btsInit } from "@reliverse/rse-rebts";

export default defineCommand({
  meta: {
    name: "init",
    description:
      "Initialize a new Better-T-Stack project, optionally with RSE monorepo structure",
    examples: [
      "rse init --bts",
      "rse init --bts my-project",
      "rse init --bts --yes",
      "rse init --bts --backend hono --database sqlite --orm drizzle",
      "rse init --bts --frontend next --backend hono --yes",
      "rse init --init-monorepo",
      "",
      "# Better-T-Stack options (requires --bts):",
      "# --bts: Initialize Better-T-Stack project (required for Better-T-Stack setup)",
      "# --name: Project name",
      "# --yes: Use default configuration",
      "# --backend: Backend framework (hono, express, fastify, elysia, convex, self, none)",
      "# --frontend: Frontend framework(s), comma-separated",
      "# --database: Database type (none, sqlite, postgres, mysql, mongodb)",
      "# --orm: ORM type (drizzle, prisma, mongoose, none)",
      "# --auth: Authentication provider",
      "# --runtime: Runtime (bun, node, workers, none)",
      "# --packageManager: Package manager (npm, pnpm, yarn, bun)",
      "# --install: Install dependencies after creation",
      "",
      "# RSE options:",
      "# --init-monorepo: Initialize RSE monorepo structure (mutually exclusive with --bts)",
    ],
  },
  args: defineArgs({
    name: {
      type: "string",
      description: "Project name (Better-T-Stack project directory name)",
    },
    yes: {
      type: "boolean",
      description: "Use default configuration",
    },
    yolo: {
      type: "boolean",
      description:
        "(WARNING - NOT RECOMMENDED) Bypass validations and compatibility checks",
    },
    verbose: {
      type: "boolean",
      description: "Show detailed result information",
    },
    database: {
      type: "string",
      description: "Database type (none, sqlite, postgres, mysql, mongodb)",
    },
    orm: {
      type: "string",
      description: "ORM type (drizzle, prisma, mongoose, none)",
    },
    auth: {
      type: "string",
      description: "Authentication provider",
    },
    payments: {
      type: "string",
      description: "Payments provider",
    },
    frontend: {
      type: "string",
      description:
        "Frontend framework(s), comma-separated (tanstack-router, react-router, tanstack-start, next, nuxt, native-bare, native-uniwind, native-unistyles, svelte, solid, none)",
    },
    addons: {
      type: "string",
      description:
        "Addon(s), comma-separated (pwa, tauri, starlight, biome, husky, ruler, turborepo, fumadocs, ultracite)",
    },
    examples: {
      type: "string",
      description: "Example(s), comma-separated",
    },
    git: {
      type: "boolean",
      description: "Initialize git repository",
    },
    packageManager: {
      type: "string",
      description: "Package manager (npm, pnpm, yarn, bun)",
    },
    install: {
      type: "boolean",
      description: "Install dependencies after creation",
    },
    dbSetup: {
      type: "string",
      description: "Database setup method",
    },
    backend: {
      type: "string",
      description:
        "Backend framework (hono, express, fastify, elysia, convex, self, none)",
    },
    runtime: {
      type: "string",
      description: "Runtime environment (bun, node, workers, none)",
    },
    api: {
      type: "string",
      description: "API type",
    },
    webDeploy: {
      type: "string",
      description: "Web deployment target",
    },
    serverDeploy: {
      type: "string",
      description: "Server deployment target",
    },
    directoryConflict: {
      type: "string",
      description: "Directory conflict resolution strategy",
    },
    renderTitle: {
      type: "boolean",
      description: "Render Better-T-Stack title",
    },
    disableAnalytics: {
      type: "boolean",
      description: "Disable analytics",
    },
    manualDb: {
      type: "boolean",
      description:
        "Skip automatic/manual database setup prompt and use manual setup",
    },
    initMonorepo: {
      type: "boolean",
      description:
        "Initialize RSE monorepo structure (mutually exclusive with Better-T-Stack setup)",
    },
    bts: {
      type: "boolean",
      description: "Initialize Better-T-Stack project (default: false)",
    },
  }),
  run: async ({ args }) => {
    try {
      // Check if running in Bun
      if (typeof process.versions.bun === "undefined") {
        logger.error("❌ This command requires Bun runtime. Sorry.");
        process.exit(1);
      }

      // Handle RSE monorepo setup or Better-T-Stack setup (mutually exclusive)
      if (args.initMonorepo) {
        // RSE monorepo setup only
        const config = await promptMonorepoConfig();

        logger.info("");
        logger.info("🔨 Generating monorepo structure...");
        logger.info("");

        await generateRootPackageJson(config);
        await generateRootFiles(config);
        await generateAllPackages(config);

        logger.info("");
        logger.info("📦 Installing dependencies...");
        logger.info("");

        await $`bun install`.cwd(config.rootPath);

        logger.info("");
        logger.success("✅ Monorepo created successfully!");

        logger.info("");
        logger.success(`📁 Location: ${config.rootPath}`);
        logger.info("");
        logger.success("To get started:");
        logger.log(`  cd ${config.rootPath}`);
        logger.log("  bun --filter '*' dev");
        logger.info("");
      } else if (args.bts) {
        // Better-T-Stack setup only
        // Prepare Better-T-Stack options
        const btsOptions: Record<string, unknown> = {};

        if (args.verbose !== undefined) btsOptions.verbose = args.verbose;
        if (args.yes !== undefined) btsOptions.yes = args.yes;
        if (args.yolo !== undefined) btsOptions.yolo = args.yolo;
        if (args.database) btsOptions.database = args.database;
        if (args.orm) btsOptions.orm = args.orm;
        if (args.auth) btsOptions.auth = args.auth;
        if (args.payments) btsOptions.payments = args.payments;
        if (args.frontend) {
          btsOptions.frontend = args.frontend
            .split(",")
            .map((f) => f.trim())
            .filter((f) => f);
        }
        if (args.addons) {
          btsOptions.addons = args.addons
            .split(",")
            .map((a) => a.trim())
            .filter((a) => a);
        }
        if (args.examples) {
          btsOptions.examples = args.examples
            .split(",")
            .map((e) => e.trim())
            .filter((e) => e);
        }
        if (args.git !== undefined) btsOptions.git = args.git;
        if (args.packageManager) btsOptions.packageManager = args.packageManager;
        if (args.install !== undefined) btsOptions.install = args.install;
        if (args.dbSetup) btsOptions.dbSetup = args.dbSetup;
        if (args.backend) btsOptions.backend = args.backend;
        if (args.runtime) btsOptions.runtime = args.runtime;
        if (args.api) btsOptions.api = args.api;
        if (args.webDeploy) btsOptions.webDeploy = args.webDeploy;
        if (args.serverDeploy) btsOptions.serverDeploy = args.serverDeploy;
        if (args.directoryConflict)
          btsOptions.directoryConflict = args.directoryConflict;
        if (args.renderTitle !== undefined)
          btsOptions.renderTitle = args.renderTitle;
        if (args.disableAnalytics !== undefined)
          btsOptions.disableAnalytics = args.disableAnalytics;
        if (args.manualDb !== undefined) btsOptions.manualDb = args.manualDb;

        logger.info("");
        logger.info("🚀 Initializing Better-T-Stack project...");
        logger.info("");
        const btsResult = await btsInit(args.name, btsOptions);

        if (!btsResult || !btsResult.success) {
          logger.error("❌ Failed to initialize Better-T-Stack project");
          process.exit(1);
        }

        logger.info("");
        logger.success("✅ Better-T-Stack project initialized successfully!");

        logger.info("");
        if (btsResult.projectDirectory) {
          logger.success(`📁 Better-T-Stack project location: ${btsResult.projectDirectory}`);
        }
        logger.info("");
      } else {
        logger.info("");
        logger.info("Please specify either --bts or --init-monorepo");
        logger.info("");
        logger.info("Examples:");
        logger.info("  rse init --bts");
        logger.info("  rse init --bts my-project --backend hono");
        logger.info("  rse init --init-monorepo");
        logger.info("");
      }
    } catch (error) {
      logger.info("");
      logger.error("❌ Error during initialization:");

      if (error instanceof Error) {
        logger.error(error.message);
      } else {
        logger.error(String(error));
      }

      process.exit(1);
    }
  },
});
